### ISSUE TITLE
Add Google Image Search support

### ISSUE THREAD

**Issue by jkupferman** [joshlasdin/otterbot#38]
There are often times when it would be useful to do a quick image search for a person or thing when people don't know what it is. Often times we end up doing a gif search for it but there are no results.

.pic Jenna Elfman
.pic tamagotchi

You can get google image search results using this JSON endpoint: `http://ajax.googleapis.com/ajax/services/search/images?v=1.0&rsz=8&safe=active&q=cat`

It should be really similar to the gifsearch command

**Comment by joshlasdin** [comment]
Fixed in 5.1
