### ISSUE TITLE
Don't post broken images when using the .pic command

### ISSUE THREAD

**Issue by jkupferman** [joshlasdin/otterbot#43]
Right now when using the .pic command there is a decent chance that the image selected from google doesn't render in chat. Usually that is because
- The image link is broken (a 404)
- The host does not allow embedding and redirects to a full page
- The url isn't correctly rendered via plug because it contains characters that the plug image url doesn't recognize (e.g. "(")

In either case it renders a broken image link. We should check that the image can actually render for users before we post it into chat. Presumably just fetch the image url, check that the response is 200 and the content type looks like an image.

**Comment by joshlasdin** [comment]
Fixed in #44.
